### ISSUE TITLE
Tigerbeetle docker image exits with `superblock not found`

### ISSUE THREAD

**Issue by dyc3** [tigerbeetle/tigerbeetle#2076]
I'm having a bit of trouble setting up tigerbeetle for my dev environment. All I'm doing is formatting the data file with format and then running the container.

This is my `docker-compose.yml`:

```yaml
version: '3.8'

services:
  tigerbeetle:
    image: ghcr.io/coilhq/tigerbeetle:latest
    command: ["start", "--addresses=0.0.0.0:6001", "/data/0_0.tigerbeetle"]
    volumes:
      - ./data/tigerbeetle:/data
    ports:
      - "6001:6001"
    restart: unless-stopped
```

Full steps:
1. format data file
```
docker run -v $(pwd)/data/tigerbeetle:/data ghcr.io/tigerbeetle/tigerbeetle:latest format --cluster=0 --replica=0 --replica-count=1 /data/0_0.tigerbeetle
```
2. `docker-compose up`
3. See logs
```
tigerbeetle_1  | info(io): opening "0_0.tigerbeetle"...
tigerbeetle_1  | thread 1 panic: superblock not found
tigerbeetle_1  | /opt/beta-beetle/src/vsr/superblock.zig:0:0: 0x3606b7 in vsr.superblock.SuperBlockType(storage.Storage).read_sector_callback (tigerbeetle)
```
