### ISSUE TITLE
Cannot run in docker / mac

### ISSUE THREAD

**Issue by ehsannm** [tigerbeetle/tigerbeetle#3013]
This is the error we get: 

```
tiger-db-1  | 2025-06-05 04:13:46.685Z warning: a cluster id of 0 is reserved for testing and benchmarking, do not use in production
tiger-db-1  | 2025-06-05 04:13:46.685Z warning: omit --cluster=0 to randomly generate a suitable id
tiger-db-1  | 
tiger-db-1  | 2025-06-05 04:13:46.685Z error(io): io_uring is not available
tiger-db-1  | 2025-06-05 04:13:46.685Z error(io): likely cause: the syscall is disabled by sysctl, try 'sysctl -w kernel.io_uring_disabled=0'
tiger-db-1  | 2025-06-05 04:13:46.685Z error: PermissionDenied

```

and this is the docker-compose:

``` 
 tiger-db:
    image: ghcr.io/tigerbeetle/tigerbeetle:0.16.43
    command: ["format", "--cluster=0", "--replica=0", "--replica-count=1", "/data/0_0.tigerbeetle"]
#    command: "start --addresses=0.0.0.0:3000 /data/0_0.tigerbeetle"
    volumes:
      - tiger-db-vol:/data
    security_opt:
      - "seccomp=unconfined"
    ports:
      - "3030:3000"
```
