### ISSUE TITLE
Slow request warning with Go client

### ISSUE THREAD

**Issue by heartical** [tigerbeetle/tigerbeetle#3035]
I'm using the TigerBeetle Go client and getting slow request warnings like:

`warning(client): 297118419547323560683854653407164577760: on_reply: slow request, request=0 op=15 size=512 register time=593ms`

i am using docker-compose:
```
services:
  tigerbeetle-init:
    image: ghcr.io/tigerbeetle/tigerbeetle
    command: format --cluster=0 --replica=0 --replica-count=1 /data/0_0.tigerbeetle
    security_opt:
      - seccomp=unconfined
    volumes:
      - ./data:/data
    restart: "no"

  tigerbeetle:
    image: ghcr.io/tigerbeetle/tigerbeetle
    command: start --addresses=0.0.0.0:3000 /data/0_0.tigerbeetle
    security_opt:
      - seccomp=unconfined
    ports:
      - "3000:3000"
    volumes:
      - ./data:/data
    depends_on:
      - tigerbeetle-init
```

1. Is this warning expected for local development setups?
2. What are the recommended values for client_request_completion_warn_ms?
3. Should I be concerned about these warnings in a development environment?
4. Are there any configuration tweaks to improve performance locally?

this is my code:
```
// module.go
package tigerbeetle

import (
	"context"

	"go.uber.org/fx"
	"go.uber.org/zap"

	tigerbeetle_client "github.com/tigerbeetle/tigerbeetle-go"
	tigerbeetle_types "github.com/tigerbeetle/tigerbeetle-go/pkg/types"
)

const (
	tigerbeetleAddr = "127.0.0.1:3000"
)

// Module provides TigerBeetle dependencies
var Module = fx.Module("tigerbeetle",
	fx.Provide(
		NewClient,
	),
	fx.Invoke(CloseHook),
)

// Client is an interface that wraps the TigerBeetle client methods
type Client interface {
	tigerbeetle_client.Client
}

// NewClient creates a new TigerBeetle client with proper configuration
func NewClient(logger *zap.Logger) (Client, error) {
	client, err := tigerbeetle_client.NewClient(
		tigerbeetle_types.ToUint128(0),
		[]string{tigerbeetleAddr},
	)
	if err != nil {
		logger.Error("Failed to create TigerBeetle client", zap.Error(err))
		return nil, err
	}

	logger.Info("TigerBeetle client created successfully")
	return client, nil
}

// CloseHook provides a lifecycle hook to close the TigerBeetle client
func CloseHook(lc fx.Lifecycle, client Client, logger *zap.Logger) {
	lc.Append(fx.Hook{
		OnStop: func(ctx context.Context) error {
			logger.Info("Closing TigerBeetle client")
			client.Close()
			return nil
		},
	})
}
```
