### ISSUE TITLE
TB Docker container doesn't run on MacOS by default

### ISSUE THREAD

**Issue by sublimator** [tigerbeetle/tigerbeetle#92]
**Dumping the contents of some queries in the R&D slack channel here. Will create PR for docs later**

Referring to this specific image:
ghcr.io/coilhq/tigerbeetle@sha256:576957b8d4fadd03de01ab3983529d73d6767cd834aa8786340fc67fcd39cb69

I was looking at the rafiki repo the other day with the ultimate goal of hooking up the extension to the OP endpoints.

I tried running the tests but they were failing:
```
Error: Log stream ended and message "/initialized data file/" was not received for 7bc2cc481bc4a0b0381456c5c61e7c73f70f87b12feb0483a6e0f0efabc58d4e
    at LineStream.<anonymous> (/Users/nicholasdudfield/projects/rafiki/.yarn/cache/testcontainers-npm-7.20.4-706f1bf23f-cb141138ae.zip/node_modules/testcontainers/dist/wait-strategy.js:112:28)
    at LineStream.emit (node:events:526:28)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) 
```

I traced it down to the TigerBeetle init step in the jest.config.js configuration:
```
    const { name: tigerbeetleDir } = tmp.dirSync({ unsafeCleanup: true })

    await new GenericContainer(
      'ghcr.io/coilhq/tigerbeetle@sha256:576957b8d4fadd03de01ab3983529d73d6767cd834aa8786340fc67fcd39cb69'
    )
      .withExposedPorts(TIGERBEETLE_PORT)
      .withBindMount(tigerbeetleDir, TIGERBEETLE_DIR)
      .withCmd([
        'init',
        '--cluster=' + TIGERBEETLE_CLUSTER_ID,
        '--replica=0',
        '--directory=' + TIGERBEETLE_DIR
      ])
      .withWaitStrategy(Wait.forLogMessage(/initialized data file/))
      .start()
```

I tried running it directly with my local docker:
```
docker run ghcr.io/coilhq/tigerbeetle@sha256:576957b8d4fadd03de01ab3983529d73d6767cd834aa8786340fc67fcd39cb69 --help   
```

But got this error:
```
error: SystemResources
/opt/beta-beetle/zig/lib/std/os/linux/io_uring.zig:0:0: 0x21f796 in main (tigerbeetle)
/opt/beta-beetle/zig/lib/std/os/linux/io_uring.zig:31:16: 0x21f79e in main (tigerbeetle)
/opt/beta-beetle/src/io/linux.zig:25:28: 0x21f7a6 in main (tigerbeetle)
/opt/beta-beetle/src/main.zig:23:14: 0x21f7ae in main (tigerbeetle)
```

It turns out it's related to the `RLIMIT_MEMLOCK` configuration

work arounds: 
1. `docker run --cap-add IPC_LOCK`
  - Apparently the limit is not enforced when you add the IPC_LOCK linux capability
3. `docker run --ulimit memlock=-1:-1 ... ` 
4. Set defaults in `$HOME/.docker/daemon.json`
  ```
  "default-ulimits": {
    "memlock": {
      "Hard": -1,
      "Name": "memlock",
      "Soft": -1
    }
  },
  ```

**Comment by matdehaast** [comment]
@sublimator is your machine an M1 mac? On my normal mac we have just been running the docker images in privledged mode to get around the above.

**Comment by sublimator** [comment]
> just been running the docker images in privledged mode to get around the above.

Thanks for the info. I did a quick google. 

> What is Docker Privileged Mode?
> Docker privileged mode grants a Docker container root capabilities to all devices on the host system. Running a container in privileged mode gives it the capabilities of its host machine.

**Comment by lewisdaly** [comment]
@matdehaast - I've been using privileged mode as well to get around this, but the annoying thing is that the `*.tigerbeetle` file is then owned by root, which causes problems when writing scripts to bring up/tear down tigerbeetle instances. Have you run into that problem at all? I'd rather not run my scripts as sudo...

For example, I have a docker container that runs the `tigerbeetle format ...` command, which then mounts the file to the local directory using a docker volume, but when I want to clean it up, I see that it's owned by `root`.

```yml
#docker-compose.format.yml
version: "3.7"

# Format the TB database file
networks:
  web:
    name: web

services:
  tigerbeetle:
    container_name: tigerbeetle
    image: ghcr.io/tigerbeetledb/tigerbeetle:debug
    command: "sh -c './tigerbeetle format --cluster=0 --replica=0 /data/0_0.tigerbeetle'"
    privileged: true
    entrypoint: ""
    volumes:
      - ./data:/data
```

I then run:
```
$ docker-compose -f docker-compose.format.yaml up -d tigerbeetle

# then check the permissions:
$ ls -la ./data/0_0.tigerbeetle                                                  
-rw-r--r-- 1 root root 692207616 Oct  9 17:33 ./data/0_0.tigerbeetle
```

**Comment by jorangreef** [comment]
Thanks @lewisdaly we're trying to figure this one out too and talking it through.

**Comment by eatonphil** [comment]
I'm pretty sure the way you modify who "root" is in the container is with  the global [userns-remap](https://docs.docker.com/engine/security/userns-remap/) setting. (Podman doesn't have this global-only limitation, but I also haven't been able to get TigerBeetle working in podman yet and I don't know if there's an equivalent Podman for Mac either). The `docker run` `-u/--user` flag only lets you map the main user in the container, not root. See also: https://gist.github.com/heyfluke/b8372df866ec2584f9a51ca7d7fe9ebb.

However, when I modify userns-remap on Docker for Mac, Docker crashes. There's an [issue open](https://github.com/docker/for-mac/issues/3280) for this that's been around since 2018 and hasn't been addressed by the Docker team so far.

Maybe there are other solutions I don't know of.

**Comment by sublimator** [comment]
@lewisdaly 

You might try setting memlock limits as in OP
For docker-compose, it seems to be configured here:
https://docs.docker.com/compose/compose-file/#ulimits

@matdehaast 
> @sublimator is your machine an M1 mac? 

No, it's an Intel (he says, 5 months later)

**Comment by eatonphil** [comment]
I confirmed that the flags you mentioned originally fix the issue and don't require --privileged, @sublimator. I'm adding them to docs now. Thanks!

**Comment by eatonphil** [comment]
The way I can get it working with docker-compose on mac @lewisdaly is to set the cap_add.

```
#docker-compose.format.yml
version: "3.7"

# Format the TB database file
networks:
  web:
    name: web

services:
  tigerbeetle:
    container_name: tigerbeetle
    image: ghcr.io/tigerbeetledb/tigerbeetle:debug
    command: "sh -c './tigerbeetle format --cluster=0 --replica=0 /data/0_0.tigerbeetle'"
    cap_add:
      - IPC_LOCK
    entrypoint: ""
    volumes:
      - ./data:/data
```

Then you don't need --privileged there and the data file is not owned by root.
